/* 
 * Copyright (C) 2021 Francisco Javier Rojas Garrido <frojasg1@hotmail.com>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3.0 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You may obtain a copy of the License at
 *
 *      http://www.gnu.org/licenses/lgpl-3.0.txt
 *
 */
package com.frojasg1.chesspdfbrowser.application;

import com.frojasg1.applications.common.components.internationalization.window.InternationalizationInitializationEndCallback;
import com.frojasg1.applications.common.configuration.application.BaseApplicationConfigurationInterface;
import com.frojasg1.general.desktop.view.about.GenericAboutJDialog;
import com.frojasg1.general.lib3d.components.api.about.animation.AnimationForAboutFactory;
import com.frojasg1.general.desktop.view.pdf.ImageJPanel;
import java.awt.Dimension;
import java.awt.Point;
import java.util.function.Consumer;
import javax.swing.SwingUtilities;

/**
 *
 * @author Usuario
 */
public class AboutJDialog extends GenericAboutJDialog
{
	protected static final String CONFIGURATION_BASE_FILE_NAME = "JDial_about";
	protected static final String RESOURCE_FOR_ABOUT_ICON = "com/frojasg1/chesspdfbrowser/resources/icons/App.icon.faded.png";
	public static final String ABOUT_RTF_FILE_NAME = "AboutText.rtf";

	/**
	 * Creates new form JDialAbout
	 */
	public AboutJDialog(java.awt.Frame parent, boolean modal,
						BaseApplicationConfigurationInterface applicationConfiguration,
						Consumer<InternationalizationInitializationEndCallback> initializationEndCallback,
						AnimationForAboutFactory animationFactory )
	{
		super(parent, modal, applicationConfiguration,
				RESOURCE_FOR_ABOUT_ICON, CONFIGURATION_BASE_FILE_NAME,
				ABOUT_RTF_FILE_NAME,
				animationFactory,
				initializationEndCallback);

//		initComponents();

		initOwnComponents();
	}

	protected void initOwnComponents()
	{
//		String authorEmailAddress = getAppliConf().getAuthorEmailAddress();

		SwingUtilities.invokeLater( () -> {
//			setData( authorEmailAddress );
			setText();
		});

		setRtfDocument( getAppliConf().getLanguage() );
	}

	protected void setText()
	{
		Dimension imageDimensions = getSizeOfOriginalImageJPanel();
		int xx = (int) (imageDimensions.getWidth() / 2);
		int yyIncrement = (int) (imageDimensions.getHeight() / 6);

		addTextLine( new ImageJPanel.TextLine( "Chess PDF", new Point( xx, yyIncrement * 2 ) ) );
		addTextLine( new ImageJPanel.TextLine( "browser", new Point( xx, yyIncrement * 3 ) ) );
		addTextLine( new ImageJPanel.TextLine( getVersion(), new Point( xx, yyIncrement * 4 ) ) );
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("AboutJDialog"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
