/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.frojasg1.general.desktop.view.panels.impl.file;

import com.frojasg1.general.desktop.view.panels.evt.BaseJPanelOfEvents;
import com.frojasg1.general.desktop.view.panels.evt.map.ButtonEventEntryMultiMap;
import com.frojasg1.general.desktop.view.zoom.mapper.ComponentMapper;
import com.frojasg1.general.desktop.view.zoom.mapper.ComposedComponent;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JPanel;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 *
 * @author Francisco Javier Rojas Garrido <frojasg1@hotmail.com>
 */
public class FileHandllingJPanel
	extends BaseJPanelOfEvents<FileHandlingPanelEventType, FileHandlingPanelEvent>
	implements ComposedComponent
{
	private static final Logger LOGGER = LoggerFactory.getLogger(FileHandllingJPanel.class);

	/**
	 * Creates new form PlayerNavigatorJPanel
	 */
	public FileHandllingJPanel() {
		super( FileHandlingPanelEventType.class );
	}

	public void init()
	{
		super.init();
	}

	@Override
	protected void initComponentsChild() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jB_saveAs = new javax.swing.JButton();
        jB_open = new javax.swing.JButton();
        jB_save = new javax.swing.JButton();

        setLayout(null);

        jPanel1.setLayout(null);

        jB_saveAs.setMaximumSize(new java.awt.Dimension(20, 20));
        jB_saveAs.setMinimumSize(new java.awt.Dimension(20, 20));
        jB_saveAs.setName("name=jB_saveAs,icon=com/frojasg1/generic/resources/file/saveAs.png"); // NOI18N
        jB_saveAs.setPreferredSize(new java.awt.Dimension(20, 20));
        jPanel1.add(jB_saveAs);
        jB_saveAs.setBounds(55, 5, 20, 20);

        jB_open.setMaximumSize(new java.awt.Dimension(20, 20));
        jB_open.setMinimumSize(new java.awt.Dimension(20, 20));
        jB_open.setName("name=jB_open,icon=com/frojasg1/generic/resources/file/openFile.png"); // NOI18N
        jB_open.setPreferredSize(new java.awt.Dimension(20, 20));
        jPanel1.add(jB_open);
        jB_open.setBounds(5, 5, 20, 20);

        jB_save.setMaximumSize(new java.awt.Dimension(20, 20));
        jB_save.setMinimumSize(new java.awt.Dimension(20, 20));
        jB_save.setName("name=jB_save,icon=com/frojasg1/generic/resources/file/save.png"); // NOI18N
        jB_save.setPreferredSize(new java.awt.Dimension(20, 20));
        jPanel1.add(jB_save);
        jB_save.setBounds(30, 5, 20, 20);

        add(jPanel1);
        jPanel1.setBounds(-1, 0, 80, 30);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_open;
    private javax.swing.JButton jB_save;
    private javax.swing.JButton jB_saveAs;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

	@Override
	protected JPanel getParentPanel()
	{
		return( jPanel1 );
	}

	@Override
	protected FileHandlingPanelEvent createEvent( FileHandlingPanelEventType type )
	{
		return( new FileHandlingPanelEvent( type ) );
	}

	@Override
	protected void fillMultiMap( ButtonEventEntryMultiMap<FileHandlingPanelEventType> result )
	{
		result.put("com/frojasg1/generic/resources/file/openFile.png", FileHandlingPanelEventType.OPEN, jB_open);
		result.put("com/frojasg1/generic/resources/file/saveAs.png", FileHandlingPanelEventType.SAVE_AS, jB_saveAs);
		result.put("com/frojasg1/generic/resources/file/save.png", FileHandlingPanelEventType.SAVE, jB_save);
	}

	@Override
	public void setComponentMapper(ComponentMapper compMapper)
	{
		jB_save = compMapper.mapComponent(jB_save );
		jB_open = compMapper.mapComponent(jB_open );
		jB_saveAs = compMapper.mapComponent(jB_saveAs );
		jPanel1 = compMapper.mapComponent( jPanel1 );

		super.setComponentMapper(compMapper);
	}
}
